### ISSUE TITLE
how can I import module/function from another notebook/.py file?

### ISSUE THREAD

**Issue by luojijiaren** [open-datastudio/zeppelin#12]
I mean if Zeppelin is set up on cloud by another team and I cannot touch the Zeppelin source code. 
For OOD, we need to chop code to multiple module/library. how can I import function/module from another Zeppelin notebook/.py file? or or we need to lay out the code so it's top-down and self-inclusive in only one Zeppelin notebook and then copy/paste to multiple .py files?

**Comment by Leemoonsoo** [comment]
I can think of a couple of approaches depending on your team's use case/workflow.

#### a. Package the code and then install the package before use.
 You can package code into some python package format like egg or wheel and then use them in the notebook.

 To install those packages, you can either 

 - run package installation command inside notebook (using `!<command>`)
 - or configure [precode](https://zeppelin.apache.org/docs/0.8.0/usage/interpreter/overview.html#precode) to automatically run installation command on interpreter startup
 - or pre-install the package in the container image

Because you can version control and reuse the code, this is probably a better approach if your module/library need to be reused many times.

#### b. using [z.run()](https://github.com/apache/zeppelin/blob/master/python/src/main/resources/python/zeppelin_context.py#L111-L121) api

Alternatively, you can run other notebook/paragraph using [z.run()](https://github.com/apache/zeppelin/blob/master/python/src/main/resources/python/zeppelin_context.py#L111-L121) api. For example

```
%python

# Run a paragraph from the same notebook
z.run("paragraphId")

# Run a paragraph in a different notebook
z.run("noteId", "paragraphId")

# Run all paragraphs in given notebook
z.run("noteId")
```

Note id can be found from your URL
![image](https://user-images.githubusercontent.com/1540981/93422816-7962e400-f869-11ea-9057-1f1c6f4108bb.png)

Paragraph Id can be found like
![image](https://user-images.githubusercontent.com/1540981/93422702-36087580-f869-11ea-994b-99fd2bfc7bc1.png)
